if SERVER then AddCSLuaFile "includes/modules/DirectorShared.lua" end

DIRECTOR_THREAT_NULL = -1
DIRECTOR_THREAT_HEAT = 0
DIRECTOR_THREAT_ALERT = 1
DIRECTOR_THREAT_AGGRESSIVE_SEARCH = 2
DIRECTOR_THREAT_COMBAT = 3

DIRECTOR_MUSIC_VO_WAIT = 1

SOUND_PATCH_ABSOLUTE_MINIMUM = .04 // Trust me, I tried to go lower than this
